openapi: 3.0.3
info:
  title: Transactions API
  version: 1.0.0
servers:
  - url: /api
paths:
  "/character":
    get:
      operationId: readCharacter
      x-vertx-event-bus: bvg.character
      responses:
        200:
          description: Ok
