name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'adopt'
        cache: maven

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.4
      with:
        maven-version: 3.8.6

    - name: Build
      run: mvn -B package

    - name: Publish
      uses: docker/build-push-action@v3.2.0
      with:
        push: true
        tags: com.bravecollective/bvg-backend:latest
